### ISSUE TITLE
Sticky search filters when user selects Search Again

### ISSUE THREAD

**Issue by tnadams** [embrace-call-for-code/fix-politics#6]
RFE to use sticky filters when doing a search then selecting the option to Search Again. It currently defaults back to the profile settings when logged in or blank when not logged in.

**Comment by tonypearson** [comment]
I created the "search again" for the situation where no laws were found, then decided to leave it in for all cases.
For anonymous search - I did not want to rely on Sessions/Cookie data to store this for the return.  We could pre-load with search_id from criteria database, but would need to pass this back from results.

For profile search -- if we fix this for anonymous, it would probably work for profile search also.

**Comment by tonypearson** [comment]
We would need some user research to determine if this is a good idea.  Assumption is that any changes from profile are one-off requests, and that the next time an advocate wishes to search, they are OK with being presented with default values again.
