### ISSUE TITLE
EMAIL_HOST not set when logged in

### ISSUE THREAD

**Issue by tnadams** [embrace-call-for-code/fix-politics#7]
The EMAIL_HOST environment variable is not set when user logs in. This throws the following error message when trying to Send Results from the search results page.

ERROR: EMAIL_HOST envionment variable not defined
    Joe Schmoe <joe@schmoe.com>

Also, small side issue, "envionment" needs an "r" to correct spelling in this error message. I can open another issue on that if needed.

**Comment by tonypearson** [comment]
Spelling fixed.  We have two options here:

a) If the EMAIL_HOST is not set, don't put the button on the screen in the first place.
b) currently, I put the button on the screen, and then fail gracefully with a polite message. (what it does today)

Let me know if we need to do "a"

**Comment by tonypearson** [comment]
This can wait until after tomorrow's demo

**Comment by tonypearson** [comment]
Decided to keep with option (b) above.
