### ISSUE TITLE
Change Location to a multi-select option

### ISSUE THREAD

**Issue by tnadams** [embrace-call-for-code/fix-politics#8]
In Search, Location should allow multiple options to be selected. Check boxes (like Impacts) or a multi-select drop down list would work, but gets very long once multiple locations are in the DB. Maybe an option to expand the list with check boxes at each level would work and create a better UX.

World
  - United Kingdom
     - ...
  - United States
     - Arizona
        - ...
     - Ohio

**Comment by tonypearson** [comment]
No, a person cannot be in two locations at the same time.  The search already is ancestor-search.   For example, if the hierarchy was:   world-usa-arizona-pima-tucson.    A search for "tucson' would automatically search all parent governments.  A search for Arizona would search world/usa/arizona only, and not search pima or tucson.

Multiple locations would be a major re-write of the application.
