### ISSUE TITLE
Location list is different between Location and Search views

### ISSUE THREAD

**Issue by tnadams** [embrace-call-for-code/fix-politics#9]
In the Search view, there is a "world" option under Location, which is not present in the location list under the Locations view. These lists should be pulled from the same file/DB and dynamically created to give real-time locations and keep in sync.

The same implementation should be done for the Impacts options, though these are currently in sync.

**Comment by tonypearson** [comment]
Fixed.  Since there is no world government, I will remove from both.  world is the root of the ancestor search.
